apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
    spec:
      containers:
      - name: guestbook-frontend
        # ⚠️ IMAGEN INICIAL: El pipeline la actualizará con el tag :SHA
        image: mikenarbikes/guestbook-frontend:114e0a9d8ba180166d7c75c4b14459e3ac0af43e
        ports:
        - containerPort: 5000 
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        env:
        - name: REDIS_MASTER_SERVICE_HOST
          value: redis-master # Nombre del servicio de Redis en K8s
        - name: REDIS_MASTER_SERVICE_PORT
          value: "6379"