apiVersion: v1
kind: Service
metadata:
  name: redis-master # Nombre del servicio usado en la variable de entorno del frontend
  labels:
    app: redis
    role: master
    tier: backend
spec:
  # ClusterIP: Solo accesible internamente. No se expone fuera del cluster.
  type: ClusterIP 
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend